apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: qq2
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "while true; do echo hello world; sleep 10; done"]
