apiVersion: v1
kind: PersistentVolume
metadata:
  name: podpv
  namespace: qq2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  hostPath:
    path: /mnt/data
